
services:
  ###> doctrine/doctrine-bundle ###
  database:
    image: mariadb:${DB_VERSION:-11.8.5}
    container_name: hnde80_database
    environment:
      MARIADB_ROOT_PASSWORD: ${MARIADB_ROOT_PASSWORD:-password}
      MARIADB_DATABASE: ${MARIADB_DATABASE:-hnde}
      MARIADB_USER: ${MARIADB_USER:-hndedba}
      MARIADB_PASSWORD: ${MARIADB_PASSWORD:-jjcM$1753}
      MARIADB_VERSION: ${MARIADB_VERSION:-11.8.5-MariaDB-ubu2404}
    healthcheck:
      test: ["CMD", "healthcheck.sh", "--connect", "--innodb_initialized"]
      start_period: 10s
      interval: 10s
      timeout: 5s
      retries: 3
    volumes:
      - database_data:/var/lib/mysql:rw
  ###< doctrine/doctrine-bundle ###

  phpmyadmin:
    image: phpmyadmin:latest
    container_name: hnde80_dbadmin
    environment:
      PMA_ARBITRARY: 1
      PMA_HOST: database
      PMA_PORT: 3306
      PMA_USER: root
      PMA_PASSWORD: password
      UPLOAD_LIMIT: 20M
    depends_on:
      - database
    ports:
      - 8100:80

###> sensiolabs/gotenberg-bundle ###
  gotenberg:
    image: 'gotenberg/gotenberg:8'
    container_name: hnde80_gotenberg
###< sensiolabs/gotenberg-bundle ###

volumes:
  ###> doctrine/doctrine-bundle ###
  database_data:
###< doctrine/doctrine-bundle ###
